#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="contabanca")]
	public partial class BaseDeDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_acceso(tbl_acceso instance);
    partial void Updatetbl_acceso(tbl_acceso instance);
    partial void Deletetbl_acceso(tbl_acceso instance);
    partial void Inserttbl_VentasDiarias(tbl_VentasDiarias instance);
    partial void Updatetbl_VentasDiarias(tbl_VentasDiarias instance);
    partial void Deletetbl_VentasDiarias(tbl_VentasDiarias instance);
    partial void Inserttbl_CajaChica(tbl_CajaChica instance);
    partial void Updatetbl_CajaChica(tbl_CajaChica instance);
    partial void Deletetbl_CajaChica(tbl_CajaChica instance);
    partial void Inserttbl_CatalogoCuenta(tbl_CatalogoCuenta instance);
    partial void Updatetbl_CatalogoCuenta(tbl_CatalogoCuenta instance);
    partial void Deletetbl_CatalogoCuenta(tbl_CatalogoCuenta instance);
    partial void Inserttbl_categoria(tbl_categoria instance);
    partial void Updatetbl_categoria(tbl_categoria instance);
    partial void Deletetbl_categoria(tbl_categoria instance);
    partial void InsertTbl_Clientes__credito(Tbl_Clientes__credito instance);
    partial void UpdateTbl_Clientes__credito(Tbl_Clientes__credito instance);
    partial void DeleteTbl_Clientes__credito(Tbl_Clientes__credito instance);
    partial void Inserttbl_detalle_venta(tbl_detalle_venta instance);
    partial void Updatetbl_detalle_venta(tbl_detalle_venta instance);
    partial void Deletetbl_detalle_venta(tbl_detalle_venta instance);
    partial void Inserttbl_EgresosCaja(tbl_EgresosCaja instance);
    partial void Updatetbl_EgresosCaja(tbl_EgresosCaja instance);
    partial void Deletetbl_EgresosCaja(tbl_EgresosCaja instance);
    partial void InsertTbl_Factura(Tbl_Factura instance);
    partial void UpdateTbl_Factura(Tbl_Factura instance);
    partial void DeleteTbl_Factura(Tbl_Factura instance);
    partial void Inserttbl_IngresosDeCaja(tbl_IngresosDeCaja instance);
    partial void Updatetbl_IngresosDeCaja(tbl_IngresosDeCaja instance);
    partial void Deletetbl_IngresosDeCaja(tbl_IngresosDeCaja instance);
    partial void Inserttbl_IngresosPorFactura(tbl_IngresosPorFactura instance);
    partial void Updatetbl_IngresosPorFactura(tbl_IngresosPorFactura instance);
    partial void Deletetbl_IngresosPorFactura(tbl_IngresosPorFactura instance);
    partial void Inserttbl_producto(tbl_producto instance);
    partial void Updatetbl_producto(tbl_producto instance);
    partial void Deletetbl_producto(tbl_producto instance);
    partial void Inserttbl_Tipo(tbl_Tipo instance);
    partial void Updatetbl_Tipo(tbl_Tipo instance);
    partial void Deletetbl_Tipo(tbl_Tipo instance);
    partial void Inserttbl_vendedor(tbl_vendedor instance);
    partial void Updatetbl_vendedor(tbl_vendedor instance);
    partial void Deletetbl_vendedor(tbl_vendedor instance);
    #endregion
		
		public BaseDeDatosDataContext() : 
				base(global::Clases.Properties.Settings.Default.contabancaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDeDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_acceso> tbl_acceso
		{
			get
			{
				return this.GetTable<tbl_acceso>();
			}
		}
		
		public System.Data.Linq.Table<tbl_VentasDiarias> tbl_VentasDiarias
		{
			get
			{
				return this.GetTable<tbl_VentasDiarias>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CajaChica> tbl_CajaChica
		{
			get
			{
				return this.GetTable<tbl_CajaChica>();
			}
		}
		
		public System.Data.Linq.Table<tbl_CatalogoCuenta> tbl_CatalogoCuenta
		{
			get
			{
				return this.GetTable<tbl_CatalogoCuenta>();
			}
		}
		
		public System.Data.Linq.Table<tbl_categoria> tbl_categoria
		{
			get
			{
				return this.GetTable<tbl_categoria>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Clientes__credito> Tbl_Clientes__credito
		{
			get
			{
				return this.GetTable<Tbl_Clientes__credito>();
			}
		}
		
		public System.Data.Linq.Table<tbl_detalle_venta> tbl_detalle_venta
		{
			get
			{
				return this.GetTable<tbl_detalle_venta>();
			}
		}
		
		public System.Data.Linq.Table<tbl_EgresosCaja> tbl_EgresosCaja
		{
			get
			{
				return this.GetTable<tbl_EgresosCaja>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Existencia> tbl_Existencia
		{
			get
			{
				return this.GetTable<tbl_Existencia>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Factura> Tbl_Factura
		{
			get
			{
				return this.GetTable<Tbl_Factura>();
			}
		}
		
		public System.Data.Linq.Table<tbl_IngresosDeCaja> tbl_IngresosDeCaja
		{
			get
			{
				return this.GetTable<tbl_IngresosDeCaja>();
			}
		}
		
		public System.Data.Linq.Table<tbl_IngresosPorFactura> tbl_IngresosPorFactura
		{
			get
			{
				return this.GetTable<tbl_IngresosPorFactura>();
			}
		}
		
		public System.Data.Linq.Table<tbl_producto> tbl_producto
		{
			get
			{
				return this.GetTable<tbl_producto>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Tipo> tbl_Tipo
		{
			get
			{
				return this.GetTable<tbl_Tipo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_vendedor> tbl_vendedor
		{
			get
			{
				return this.GetTable<tbl_vendedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_acceso")]
	public partial class tbl_acceso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_acceso;
		
		private string _ususario;
		
		private string _contraseña;
		
		private string _Cargo;
		
		private EntityRef<tbl_vendedor> _tbl_vendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_accesoChanging(int value);
    partial void Onid_accesoChanged();
    partial void OnususarioChanging(string value);
    partial void OnususarioChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    #endregion
		
		public tbl_acceso()
		{
			this._tbl_vendedor = default(EntityRef<tbl_vendedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_acceso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_acceso
		{
			get
			{
				return this._id_acceso;
			}
			set
			{
				if ((this._id_acceso != value))
				{
					if (this._tbl_vendedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_accesoChanging(value);
					this.SendPropertyChanging();
					this._id_acceso = value;
					this.SendPropertyChanged("id_acceso");
					this.Onid_accesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ususario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ususario
		{
			get
			{
				return this._ususario;
			}
			set
			{
				if ((this._ususario != value))
				{
					this.OnususarioChanging(value);
					this.SendPropertyChanging();
					this._ususario = value;
					this.SendPropertyChanged("ususario");
					this.OnususarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_vendedor_tbl_acceso", Storage="_tbl_vendedor", ThisKey="id_acceso", OtherKey="id_vendedor", IsForeignKey=true)]
		public tbl_vendedor tbl_vendedor
		{
			get
			{
				return this._tbl_vendedor.Entity;
			}
			set
			{
				tbl_vendedor previousValue = this._tbl_vendedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_vendedor.Entity = null;
						previousValue.tbl_acceso = null;
					}
					this._tbl_vendedor.Entity = value;
					if ((value != null))
					{
						value.tbl_acceso = this;
						this._id_acceso = value.id_vendedor;
					}
					else
					{
						this._id_acceso = default(int);
					}
					this.SendPropertyChanged("tbl_vendedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_VentasDiarias")]
	public partial class tbl_VentasDiarias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Venta;
		
		private string _Producto;
		
		private decimal _VentaTotal;
		
		private decimal _Ganancias;
		
		private string _Id_TipoProducto;
		
		private EntityRef<tbl_CajaChica> _tbl_CajaChica;
		
		private EntityRef<tbl_CatalogoCuenta> _tbl_CatalogoCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_VentaChanging(int value);
    partial void OnId_VentaChanged();
    partial void OnProductoChanging(string value);
    partial void OnProductoChanged();
    partial void OnVentaTotalChanging(decimal value);
    partial void OnVentaTotalChanged();
    partial void OnGananciasChanging(decimal value);
    partial void OnGananciasChanged();
    partial void OnId_TipoProductoChanging(string value);
    partial void OnId_TipoProductoChanged();
    #endregion
		
		public tbl_VentasDiarias()
		{
			this._tbl_CajaChica = default(EntityRef<tbl_CajaChica>);
			this._tbl_CatalogoCuenta = default(EntityRef<tbl_CatalogoCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Venta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Venta
		{
			get
			{
				return this._Id_Venta;
			}
			set
			{
				if ((this._Id_Venta != value))
				{
					this.OnId_VentaChanging(value);
					this.SendPropertyChanging();
					this._Id_Venta = value;
					this.SendPropertyChanged("Id_Venta");
					this.OnId_VentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this.OnProductoChanging(value);
					this.SendPropertyChanging();
					this._Producto = value;
					this.SendPropertyChanged("Producto");
					this.OnProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaTotal", DbType="Decimal(18,2) NOT NULL")]
		public decimal VentaTotal
		{
			get
			{
				return this._VentaTotal;
			}
			set
			{
				if ((this._VentaTotal != value))
				{
					this.OnVentaTotalChanging(value);
					this.SendPropertyChanging();
					this._VentaTotal = value;
					this.SendPropertyChanged("VentaTotal");
					this.OnVentaTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ganancias", DbType="Decimal(18,2) NOT NULL")]
		public decimal Ganancias
		{
			get
			{
				return this._Ganancias;
			}
			set
			{
				if ((this._Ganancias != value))
				{
					this.OnGananciasChanging(value);
					this.SendPropertyChanging();
					this._Ganancias = value;
					this.SendPropertyChanged("Ganancias");
					this.OnGananciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_TipoProducto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Id_TipoProducto
		{
			get
			{
				return this._Id_TipoProducto;
			}
			set
			{
				if ((this._Id_TipoProducto != value))
				{
					this.OnId_TipoProductoChanging(value);
					this.SendPropertyChanging();
					this._Id_TipoProducto = value;
					this.SendPropertyChanged("Id_TipoProducto");
					this.OnId_TipoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_VentasDiarias_tbl_CajaChica", Storage="_tbl_CajaChica", ThisKey="Id_Venta", OtherKey="Id_Caja", IsUnique=true, IsForeignKey=false)]
		public tbl_CajaChica tbl_CajaChica
		{
			get
			{
				return this._tbl_CajaChica.Entity;
			}
			set
			{
				tbl_CajaChica previousValue = this._tbl_CajaChica.Entity;
				if (((previousValue != value) 
							|| (this._tbl_CajaChica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_CajaChica.Entity = null;
						previousValue.tbl_VentasDiarias = null;
					}
					this._tbl_CajaChica.Entity = value;
					if ((value != null))
					{
						value.tbl_VentasDiarias = this;
					}
					this.SendPropertyChanged("tbl_CajaChica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_VentasDiarias_tbl_CatalogoCuenta", Storage="_tbl_CatalogoCuenta", ThisKey="Id_Venta", OtherKey="id_catalogoCuenta", IsUnique=true, IsForeignKey=false)]
		public tbl_CatalogoCuenta tbl_CatalogoCuenta
		{
			get
			{
				return this._tbl_CatalogoCuenta.Entity;
			}
			set
			{
				tbl_CatalogoCuenta previousValue = this._tbl_CatalogoCuenta.Entity;
				if (((previousValue != value) 
							|| (this._tbl_CatalogoCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_CatalogoCuenta.Entity = null;
						previousValue.tbl_VentasDiarias = null;
					}
					this._tbl_CatalogoCuenta.Entity = value;
					if ((value != null))
					{
						value.tbl_VentasDiarias = this;
					}
					this.SendPropertyChanged("tbl_CatalogoCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CajaChica")]
	public partial class tbl_CajaChica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Caja;
		
		private System.DateTime _Fecha;
		
		private decimal _TotalIngresos;
		
		private decimal _TotalEgresos;
		
		private decimal _SaldoEnCaja;
		
		private EntityRef<tbl_IngresosDeCaja> _tbl_IngresosDeCaja;
		
		private EntityRef<tbl_VentasDiarias> _tbl_VentasDiarias;
		
		private EntityRef<tbl_IngresosPorFactura> _tbl_IngresosPorFactura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CajaChanging(int value);
    partial void OnId_CajaChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnTotalIngresosChanging(decimal value);
    partial void OnTotalIngresosChanged();
    partial void OnTotalEgresosChanging(decimal value);
    partial void OnTotalEgresosChanged();
    partial void OnSaldoEnCajaChanging(decimal value);
    partial void OnSaldoEnCajaChanged();
    #endregion
		
		public tbl_CajaChica()
		{
			this._tbl_IngresosDeCaja = default(EntityRef<tbl_IngresosDeCaja>);
			this._tbl_VentasDiarias = default(EntityRef<tbl_VentasDiarias>);
			this._tbl_IngresosPorFactura = default(EntityRef<tbl_IngresosPorFactura>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Caja", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_Caja
		{
			get
			{
				return this._Id_Caja;
			}
			set
			{
				if ((this._Id_Caja != value))
				{
					if ((this._tbl_VentasDiarias.HasLoadedOrAssignedValue || this._tbl_IngresosPorFactura.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_CajaChanging(value);
					this.SendPropertyChanging();
					this._Id_Caja = value;
					this.SendPropertyChanged("Id_Caja");
					this.OnId_CajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalIngresos", DbType="Decimal(18,2) NOT NULL")]
		public decimal TotalIngresos
		{
			get
			{
				return this._TotalIngresos;
			}
			set
			{
				if ((this._TotalIngresos != value))
				{
					this.OnTotalIngresosChanging(value);
					this.SendPropertyChanging();
					this._TotalIngresos = value;
					this.SendPropertyChanged("TotalIngresos");
					this.OnTotalIngresosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalEgresos", DbType="Decimal(18,2) NOT NULL")]
		public decimal TotalEgresos
		{
			get
			{
				return this._TotalEgresos;
			}
			set
			{
				if ((this._TotalEgresos != value))
				{
					this.OnTotalEgresosChanging(value);
					this.SendPropertyChanging();
					this._TotalEgresos = value;
					this.SendPropertyChanged("TotalEgresos");
					this.OnTotalEgresosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaldoEnCaja", DbType="Decimal(18,2) NOT NULL")]
		public decimal SaldoEnCaja
		{
			get
			{
				return this._SaldoEnCaja;
			}
			set
			{
				if ((this._SaldoEnCaja != value))
				{
					this.OnSaldoEnCajaChanging(value);
					this.SendPropertyChanging();
					this._SaldoEnCaja = value;
					this.SendPropertyChanged("SaldoEnCaja");
					this.OnSaldoEnCajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_CajaChica_tbl_IngresosDeCaja", Storage="_tbl_IngresosDeCaja", ThisKey="Id_Caja", OtherKey="Id_IngresosCaja", IsUnique=true, IsForeignKey=false)]
		public tbl_IngresosDeCaja tbl_IngresosDeCaja
		{
			get
			{
				return this._tbl_IngresosDeCaja.Entity;
			}
			set
			{
				tbl_IngresosDeCaja previousValue = this._tbl_IngresosDeCaja.Entity;
				if (((previousValue != value) 
							|| (this._tbl_IngresosDeCaja.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_IngresosDeCaja.Entity = null;
						previousValue.tbl_CajaChica = null;
					}
					this._tbl_IngresosDeCaja.Entity = value;
					if ((value != null))
					{
						value.tbl_CajaChica = this;
					}
					this.SendPropertyChanged("tbl_IngresosDeCaja");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_VentasDiarias_tbl_CajaChica", Storage="_tbl_VentasDiarias", ThisKey="Id_Caja", OtherKey="Id_Venta", IsForeignKey=true)]
		public tbl_VentasDiarias tbl_VentasDiarias
		{
			get
			{
				return this._tbl_VentasDiarias.Entity;
			}
			set
			{
				tbl_VentasDiarias previousValue = this._tbl_VentasDiarias.Entity;
				if (((previousValue != value) 
							|| (this._tbl_VentasDiarias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_VentasDiarias.Entity = null;
						previousValue.tbl_CajaChica = null;
					}
					this._tbl_VentasDiarias.Entity = value;
					if ((value != null))
					{
						value.tbl_CajaChica = this;
						this._Id_Caja = value.Id_Venta;
					}
					else
					{
						this._Id_Caja = default(int);
					}
					this.SendPropertyChanged("tbl_VentasDiarias");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_IngresosPorFactura_tbl_CajaChica", Storage="_tbl_IngresosPorFactura", ThisKey="Id_Caja", OtherKey="Id_IngresosPorFactura", IsForeignKey=true)]
		public tbl_IngresosPorFactura tbl_IngresosPorFactura
		{
			get
			{
				return this._tbl_IngresosPorFactura.Entity;
			}
			set
			{
				tbl_IngresosPorFactura previousValue = this._tbl_IngresosPorFactura.Entity;
				if (((previousValue != value) 
							|| (this._tbl_IngresosPorFactura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_IngresosPorFactura.Entity = null;
						previousValue.tbl_CajaChica = null;
					}
					this._tbl_IngresosPorFactura.Entity = value;
					if ((value != null))
					{
						value.tbl_CajaChica = this;
						this._Id_Caja = value.Id_IngresosPorFactura;
					}
					else
					{
						this._Id_Caja = default(int);
					}
					this.SendPropertyChanged("tbl_IngresosPorFactura");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_CatalogoCuenta")]
	public partial class tbl_CatalogoCuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_catalogoCuenta;
		
		private bool _Activo;
		
		private bool _Pasivo;
		
		private decimal _Capital;
		
		private decimal _Debe;
		
		private decimal _Haber;
		
		private EntityRef<tbl_VentasDiarias> _tbl_VentasDiarias;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_catalogoCuentaChanging(int value);
    partial void Onid_catalogoCuentaChanged();
    partial void OnActivoChanging(bool value);
    partial void OnActivoChanged();
    partial void OnPasivoChanging(bool value);
    partial void OnPasivoChanged();
    partial void OnCapitalChanging(decimal value);
    partial void OnCapitalChanged();
    partial void OnDebeChanging(decimal value);
    partial void OnDebeChanged();
    partial void OnHaberChanging(decimal value);
    partial void OnHaberChanged();
    #endregion
		
		public tbl_CatalogoCuenta()
		{
			this._tbl_VentasDiarias = default(EntityRef<tbl_VentasDiarias>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_catalogoCuenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_catalogoCuenta
		{
			get
			{
				return this._id_catalogoCuenta;
			}
			set
			{
				if ((this._id_catalogoCuenta != value))
				{
					if (this._tbl_VentasDiarias.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_catalogoCuentaChanging(value);
					this.SendPropertyChanging();
					this._id_catalogoCuenta = value;
					this.SendPropertyChanged("id_catalogoCuenta");
					this.Onid_catalogoCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasivo", DbType="Bit NOT NULL")]
		public bool Pasivo
		{
			get
			{
				return this._Pasivo;
			}
			set
			{
				if ((this._Pasivo != value))
				{
					this.OnPasivoChanging(value);
					this.SendPropertyChanging();
					this._Pasivo = value;
					this.SendPropertyChanged("Pasivo");
					this.OnPasivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="Decimal(18,2) NOT NULL")]
		public decimal Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debe", DbType="Decimal(18,2) NOT NULL")]
		public decimal Debe
		{
			get
			{
				return this._Debe;
			}
			set
			{
				if ((this._Debe != value))
				{
					this.OnDebeChanging(value);
					this.SendPropertyChanging();
					this._Debe = value;
					this.SendPropertyChanged("Debe");
					this.OnDebeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haber", DbType="Decimal(18,2) NOT NULL")]
		public decimal Haber
		{
			get
			{
				return this._Haber;
			}
			set
			{
				if ((this._Haber != value))
				{
					this.OnHaberChanging(value);
					this.SendPropertyChanging();
					this._Haber = value;
					this.SendPropertyChanged("Haber");
					this.OnHaberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_VentasDiarias_tbl_CatalogoCuenta", Storage="_tbl_VentasDiarias", ThisKey="id_catalogoCuenta", OtherKey="Id_Venta", IsForeignKey=true)]
		public tbl_VentasDiarias tbl_VentasDiarias
		{
			get
			{
				return this._tbl_VentasDiarias.Entity;
			}
			set
			{
				tbl_VentasDiarias previousValue = this._tbl_VentasDiarias.Entity;
				if (((previousValue != value) 
							|| (this._tbl_VentasDiarias.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_VentasDiarias.Entity = null;
						previousValue.tbl_CatalogoCuenta = null;
					}
					this._tbl_VentasDiarias.Entity = value;
					if ((value != null))
					{
						value.tbl_CatalogoCuenta = this;
						this._id_catalogoCuenta = value.Id_Venta;
					}
					else
					{
						this._id_catalogoCuenta = default(int);
					}
					this.SendPropertyChanged("tbl_VentasDiarias");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_categoria")]
	public partial class tbl_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _categoria;
		
		private string _estado;
		
		private EntitySet<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public tbl_categoria()
		{
			this._tbl_producto = new EntitySet<tbl_producto>(new Action<tbl_producto>(this.attach_tbl_producto), new Action<tbl_producto>(this.detach_tbl_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_producto", Storage="_tbl_producto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<tbl_producto> tbl_producto
		{
			get
			{
				return this._tbl_producto;
			}
			set
			{
				this._tbl_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = this;
		}
		
		private void detach_tbl_producto(tbl_producto entity)
		{
			this.SendPropertyChanging();
			entity.tbl_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Tbl_Clientes _credito]")]
	public partial class Tbl_Clientes__credito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Cliente;
		
		private string _Nombre;
		
		private string _apellidos;
		
		private string _Direccion;
		
		private int _Telefono;
		
		private string _Cedula;
		
		private EntitySet<Tbl_Factura> _Tbl_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ClienteChanging(int value);
    partial void Onid_ClienteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(int value);
    partial void OnTelefonoChanged();
    partial void OnCedulaChanging(string value);
    partial void OnCedulaChanged();
    #endregion
		
		public Tbl_Clientes__credito()
		{
			this._Tbl_Factura = new EntitySet<Tbl_Factura>(new Action<Tbl_Factura>(this.attach_Tbl_Factura), new Action<Tbl_Factura>(this.detach_Tbl_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Cliente
		{
			get
			{
				return this._id_Cliente;
			}
			set
			{
				if ((this._id_Cliente != value))
				{
					this.Onid_ClienteChanging(value);
					this.SendPropertyChanging();
					this._id_Cliente = value;
					this.SendPropertyChanged("id_Cliente");
					this.Onid_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this.OnCedulaChanging(value);
					this.SendPropertyChanging();
					this._Cedula = value;
					this.SendPropertyChanged("Cedula");
					this.OnCedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Clientes__credito_Tbl_Factura", Storage="_Tbl_Factura", ThisKey="id_Cliente", OtherKey="id_ClienteCredito")]
		public EntitySet<Tbl_Factura> Tbl_Factura
		{
			get
			{
				return this._Tbl_Factura;
			}
			set
			{
				this._Tbl_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Factura(Tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Clientes__credito = this;
		}
		
		private void detach_Tbl_Factura(Tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Clientes__credito = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_detalle_venta")]
	public partial class tbl_detalle_venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venta;
		
		private int _id_factura;
		
		private int _id_producto;
		
		private decimal _precio_unit;
		
		private decimal _cantidad;
		
		private decimal _descuento;
		
		private decimal _total_venta;
		
		private EntityRef<Tbl_Factura> _Tbl_Factura;
		
		private EntityRef<tbl_producto> _tbl_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ventaChanging(int value);
    partial void Onid_ventaChanged();
    partial void Onid_facturaChanging(int value);
    partial void Onid_facturaChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void Onprecio_unitChanging(decimal value);
    partial void Onprecio_unitChanged();
    partial void OncantidadChanging(decimal value);
    partial void OncantidadChanged();
    partial void OndescuentoChanging(decimal value);
    partial void OndescuentoChanged();
    partial void Ontotal_ventaChanging(decimal value);
    partial void Ontotal_ventaChanged();
    #endregion
		
		public tbl_detalle_venta()
		{
			this._Tbl_Factura = default(EntityRef<Tbl_Factura>);
			this._tbl_producto = default(EntityRef<tbl_producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venta
		{
			get
			{
				return this._id_venta;
			}
			set
			{
				if ((this._id_venta != value))
				{
					if (this._tbl_producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ventaChanging(value);
					this.SendPropertyChanging();
					this._id_venta = value;
					this.SendPropertyChanged("id_venta");
					this.Onid_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_factura", DbType="Int NOT NULL")]
		public int id_factura
		{
			get
			{
				return this._id_factura;
			}
			set
			{
				if ((this._id_factura != value))
				{
					if (this._Tbl_Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_facturaChanging(value);
					this.SendPropertyChanging();
					this._id_factura = value;
					this.SendPropertyChanged("id_factura");
					this.Onid_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_unit", DbType="Decimal(18,2) NOT NULL")]
		public decimal precio_unit
		{
			get
			{
				return this._precio_unit;
			}
			set
			{
				if ((this._precio_unit != value))
				{
					this.Onprecio_unitChanging(value);
					this.SendPropertyChanging();
					this._precio_unit = value;
					this.SendPropertyChanged("precio_unit");
					this.Onprecio_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Decimal(18,2) NOT NULL")]
		public decimal cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento", DbType="Decimal(18,2) NOT NULL")]
		public decimal descuento
		{
			get
			{
				return this._descuento;
			}
			set
			{
				if ((this._descuento != value))
				{
					this.OndescuentoChanging(value);
					this.SendPropertyChanging();
					this._descuento = value;
					this.SendPropertyChanged("descuento");
					this.OndescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_venta", DbType="Decimal(18,2) NOT NULL")]
		public decimal total_venta
		{
			get
			{
				return this._total_venta;
			}
			set
			{
				if ((this._total_venta != value))
				{
					this.Ontotal_ventaChanging(value);
					this.SendPropertyChanging();
					this._total_venta = value;
					this.SendPropertyChanged("total_venta");
					this.Ontotal_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Factura_tbl_detalle_venta", Storage="_Tbl_Factura", ThisKey="id_factura", OtherKey="id_Factura", IsForeignKey=true)]
		public Tbl_Factura Tbl_Factura
		{
			get
			{
				return this._Tbl_Factura.Entity;
			}
			set
			{
				Tbl_Factura previousValue = this._Tbl_Factura.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Factura.Entity = null;
						previousValue.tbl_detalle_venta.Remove(this);
					}
					this._Tbl_Factura.Entity = value;
					if ((value != null))
					{
						value.tbl_detalle_venta.Add(this);
						this._id_factura = value.id_Factura;
					}
					else
					{
						this._id_factura = default(int);
					}
					this.SendPropertyChanged("Tbl_Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_detalle_venta", Storage="_tbl_producto", ThisKey="id_venta", OtherKey="id_producto", IsForeignKey=true)]
		public tbl_producto tbl_producto
		{
			get
			{
				return this._tbl_producto.Entity;
			}
			set
			{
				tbl_producto previousValue = this._tbl_producto.Entity;
				if (((previousValue != value) 
							|| (this._tbl_producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_producto.Entity = null;
						previousValue.tbl_detalle_venta = null;
					}
					this._tbl_producto.Entity = value;
					if ((value != null))
					{
						value.tbl_detalle_venta = this;
						this._id_venta = value.id_producto;
					}
					else
					{
						this._id_venta = default(int);
					}
					this.SendPropertyChanged("tbl_producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_EgresosCaja")]
	public partial class tbl_EgresosCaja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_EgresosCaja;
		
		private int _Id_Caja;
		
		private double _Monto;
		
		private System.DateTime _Fecha_Hora;
		
		private EntityRef<tbl_IngresosDeCaja> _tbl_IngresosDeCaja;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_EgresosCajaChanging(int value);
    partial void OnId_EgresosCajaChanged();
    partial void OnId_CajaChanging(int value);
    partial void OnId_CajaChanged();
    partial void OnMontoChanging(double value);
    partial void OnMontoChanged();
    partial void OnFecha_HoraChanging(System.DateTime value);
    partial void OnFecha_HoraChanged();
    #endregion
		
		public tbl_EgresosCaja()
		{
			this._tbl_IngresosDeCaja = default(EntityRef<tbl_IngresosDeCaja>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_EgresosCaja", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_EgresosCaja
		{
			get
			{
				return this._Id_EgresosCaja;
			}
			set
			{
				if ((this._Id_EgresosCaja != value))
				{
					if (this._tbl_IngresosDeCaja.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_EgresosCajaChanging(value);
					this.SendPropertyChanging();
					this._Id_EgresosCaja = value;
					this.SendPropertyChanged("Id_EgresosCaja");
					this.OnId_EgresosCajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Caja", DbType="Int NOT NULL")]
		public int Id_Caja
		{
			get
			{
				return this._Id_Caja;
			}
			set
			{
				if ((this._Id_Caja != value))
				{
					this.OnId_CajaChanging(value);
					this.SendPropertyChanging();
					this._Id_Caja = value;
					this.SendPropertyChanged("Id_Caja");
					this.OnId_CajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Float NOT NULL")]
		public double Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Hora", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Hora
		{
			get
			{
				return this._Fecha_Hora;
			}
			set
			{
				if ((this._Fecha_Hora != value))
				{
					this.OnFecha_HoraChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Hora = value;
					this.SendPropertyChanged("Fecha_Hora");
					this.OnFecha_HoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_IngresosDeCaja_tbl_EgresosCaja", Storage="_tbl_IngresosDeCaja", ThisKey="Id_EgresosCaja", OtherKey="Id_IngresosCaja", IsForeignKey=true)]
		public tbl_IngresosDeCaja tbl_IngresosDeCaja
		{
			get
			{
				return this._tbl_IngresosDeCaja.Entity;
			}
			set
			{
				tbl_IngresosDeCaja previousValue = this._tbl_IngresosDeCaja.Entity;
				if (((previousValue != value) 
							|| (this._tbl_IngresosDeCaja.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_IngresosDeCaja.Entity = null;
						previousValue.tbl_EgresosCaja = null;
					}
					this._tbl_IngresosDeCaja.Entity = value;
					if ((value != null))
					{
						value.tbl_EgresosCaja = this;
						this._Id_EgresosCaja = value.Id_IngresosCaja;
					}
					else
					{
						this._Id_EgresosCaja = default(int);
					}
					this.SendPropertyChanged("tbl_IngresosDeCaja");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Existencia")]
	public partial class tbl_Existencia
	{
		
		private int _id_Existencia;
		
		private string _NombreExistencia;
		
		private decimal _PrecioUnidad;
		
		private string _UnidadExistencia;
		
		private int _id_categoria;
		
		public tbl_Existencia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Existencia", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_Existencia
		{
			get
			{
				return this._id_Existencia;
			}
			set
			{
				if ((this._id_Existencia != value))
				{
					this._id_Existencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreExistencia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreExistencia
		{
			get
			{
				return this._NombreExistencia;
			}
			set
			{
				if ((this._NombreExistencia != value))
				{
					this._NombreExistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnidad", DbType="Decimal(18,2) NOT NULL")]
		public decimal PrecioUnidad
		{
			get
			{
				return this._PrecioUnidad;
			}
			set
			{
				if ((this._PrecioUnidad != value))
				{
					this._PrecioUnidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadExistencia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UnidadExistencia
		{
			get
			{
				return this._UnidadExistencia;
			}
			set
			{
				if ((this._UnidadExistencia != value))
				{
					this._UnidadExistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL")]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this._id_categoria = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Factura")]
	public partial class Tbl_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Factura;
		
		private int _id_ClienteCredito;
		
		private int _id_Tipo;
		
		private int _id_vendedor;
		
		private System.DateTime _Fecha;
		
		private string _Nombre_ClienteContado;
		
		private string _Estado;
		
		private decimal _Sub_Total;
		
		private decimal _Iva;
		
		private decimal _Total_Factura;
		
		private EntitySet<tbl_detalle_venta> _tbl_detalle_venta;
		
		private EntityRef<Tbl_Clientes__credito> _Tbl_Clientes__credito;
		
		private EntityRef<tbl_Tipo> _tbl_Tipo;
		
		private EntityRef<tbl_vendedor> _tbl_vendedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_FacturaChanging(int value);
    partial void Onid_FacturaChanged();
    partial void Onid_ClienteCreditoChanging(int value);
    partial void Onid_ClienteCreditoChanged();
    partial void Onid_TipoChanging(int value);
    partial void Onid_TipoChanged();
    partial void Onid_vendedorChanging(int value);
    partial void Onid_vendedorChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnNombre_ClienteContadoChanging(string value);
    partial void OnNombre_ClienteContadoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnSub_TotalChanging(decimal value);
    partial void OnSub_TotalChanged();
    partial void OnIvaChanging(decimal value);
    partial void OnIvaChanged();
    partial void OnTotal_FacturaChanging(decimal value);
    partial void OnTotal_FacturaChanged();
    #endregion
		
		public Tbl_Factura()
		{
			this._tbl_detalle_venta = new EntitySet<tbl_detalle_venta>(new Action<tbl_detalle_venta>(this.attach_tbl_detalle_venta), new Action<tbl_detalle_venta>(this.detach_tbl_detalle_venta));
			this._Tbl_Clientes__credito = default(EntityRef<Tbl_Clientes__credito>);
			this._tbl_Tipo = default(EntityRef<tbl_Tipo>);
			this._tbl_vendedor = default(EntityRef<tbl_vendedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Factura", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Factura
		{
			get
			{
				return this._id_Factura;
			}
			set
			{
				if ((this._id_Factura != value))
				{
					this.Onid_FacturaChanging(value);
					this.SendPropertyChanging();
					this._id_Factura = value;
					this.SendPropertyChanged("id_Factura");
					this.Onid_FacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ClienteCredito", DbType="Int NOT NULL")]
		public int id_ClienteCredito
		{
			get
			{
				return this._id_ClienteCredito;
			}
			set
			{
				if ((this._id_ClienteCredito != value))
				{
					if (this._Tbl_Clientes__credito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ClienteCreditoChanging(value);
					this.SendPropertyChanging();
					this._id_ClienteCredito = value;
					this.SendPropertyChanged("id_ClienteCredito");
					this.Onid_ClienteCreditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Tipo", DbType="Int NOT NULL")]
		public int id_Tipo
		{
			get
			{
				return this._id_Tipo;
			}
			set
			{
				if ((this._id_Tipo != value))
				{
					if (this._tbl_Tipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_TipoChanging(value);
					this.SendPropertyChanging();
					this._id_Tipo = value;
					this.SendPropertyChanged("id_Tipo");
					this.Onid_TipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vendedor", DbType="Int NOT NULL")]
		public int id_vendedor
		{
			get
			{
				return this._id_vendedor;
			}
			set
			{
				if ((this._id_vendedor != value))
				{
					if (this._tbl_vendedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendedorChanging(value);
					this.SendPropertyChanging();
					this._id_vendedor = value;
					this.SendPropertyChanged("id_vendedor");
					this.Onid_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_ClienteContado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre_ClienteContado
		{
			get
			{
				return this._Nombre_ClienteContado;
			}
			set
			{
				if ((this._Nombre_ClienteContado != value))
				{
					this.OnNombre_ClienteContadoChanging(value);
					this.SendPropertyChanging();
					this._Nombre_ClienteContado = value;
					this.SendPropertyChanged("Nombre_ClienteContado");
					this.OnNombre_ClienteContadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sub_Total", DbType="Decimal(18,2) NOT NULL")]
		public decimal Sub_Total
		{
			get
			{
				return this._Sub_Total;
			}
			set
			{
				if ((this._Sub_Total != value))
				{
					this.OnSub_TotalChanging(value);
					this.SendPropertyChanging();
					this._Sub_Total = value;
					this.SendPropertyChanged("Sub_Total");
					this.OnSub_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iva", DbType="Decimal(18,2) NOT NULL")]
		public decimal Iva
		{
			get
			{
				return this._Iva;
			}
			set
			{
				if ((this._Iva != value))
				{
					this.OnIvaChanging(value);
					this.SendPropertyChanging();
					this._Iva = value;
					this.SendPropertyChanged("Iva");
					this.OnIvaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Factura", DbType="Decimal(18,2) NOT NULL")]
		public decimal Total_Factura
		{
			get
			{
				return this._Total_Factura;
			}
			set
			{
				if ((this._Total_Factura != value))
				{
					this.OnTotal_FacturaChanging(value);
					this.SendPropertyChanging();
					this._Total_Factura = value;
					this.SendPropertyChanged("Total_Factura");
					this.OnTotal_FacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Factura_tbl_detalle_venta", Storage="_tbl_detalle_venta", ThisKey="id_Factura", OtherKey="id_factura")]
		public EntitySet<tbl_detalle_venta> tbl_detalle_venta
		{
			get
			{
				return this._tbl_detalle_venta;
			}
			set
			{
				this._tbl_detalle_venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Clientes__credito_Tbl_Factura", Storage="_Tbl_Clientes__credito", ThisKey="id_ClienteCredito", OtherKey="id_Cliente", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_Clientes__credito Tbl_Clientes__credito
		{
			get
			{
				return this._Tbl_Clientes__credito.Entity;
			}
			set
			{
				Tbl_Clientes__credito previousValue = this._Tbl_Clientes__credito.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Clientes__credito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Clientes__credito.Entity = null;
						previousValue.Tbl_Factura.Remove(this);
					}
					this._Tbl_Clientes__credito.Entity = value;
					if ((value != null))
					{
						value.Tbl_Factura.Add(this);
						this._id_ClienteCredito = value.id_Cliente;
					}
					else
					{
						this._id_ClienteCredito = default(int);
					}
					this.SendPropertyChanged("Tbl_Clientes__credito");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Tipo_Tbl_Factura", Storage="_tbl_Tipo", ThisKey="id_Tipo", OtherKey="id_tipo", IsForeignKey=true)]
		public tbl_Tipo tbl_Tipo
		{
			get
			{
				return this._tbl_Tipo.Entity;
			}
			set
			{
				tbl_Tipo previousValue = this._tbl_Tipo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Tipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Tipo.Entity = null;
						previousValue.Tbl_Factura.Remove(this);
					}
					this._tbl_Tipo.Entity = value;
					if ((value != null))
					{
						value.Tbl_Factura.Add(this);
						this._id_Tipo = value.id_tipo;
					}
					else
					{
						this._id_Tipo = default(int);
					}
					this.SendPropertyChanged("tbl_Tipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_vendedor_Tbl_Factura", Storage="_tbl_vendedor", ThisKey="id_vendedor", OtherKey="id_vendedor", IsForeignKey=true)]
		public tbl_vendedor tbl_vendedor
		{
			get
			{
				return this._tbl_vendedor.Entity;
			}
			set
			{
				tbl_vendedor previousValue = this._tbl_vendedor.Entity;
				if (((previousValue != value) 
							|| (this._tbl_vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_vendedor.Entity = null;
						previousValue.Tbl_Factura.Remove(this);
					}
					this._tbl_vendedor.Entity = value;
					if ((value != null))
					{
						value.Tbl_Factura.Add(this);
						this._id_vendedor = value.id_vendedor;
					}
					else
					{
						this._id_vendedor = default(int);
					}
					this.SendPropertyChanged("tbl_vendedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_detalle_venta(tbl_detalle_venta entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Factura = this;
		}
		
		private void detach_tbl_detalle_venta(tbl_detalle_venta entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_IngresosDeCaja")]
	public partial class tbl_IngresosDeCaja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_IngresosCaja;
		
		private int _Id_Caja;
		
		private double _Monto;
		
		private System.DateTime _Fecha_Hora;
		
		private EntityRef<tbl_EgresosCaja> _tbl_EgresosCaja;
		
		private EntityRef<tbl_CajaChica> _tbl_CajaChica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_IngresosCajaChanging(int value);
    partial void OnId_IngresosCajaChanged();
    partial void OnId_CajaChanging(int value);
    partial void OnId_CajaChanged();
    partial void OnMontoChanging(double value);
    partial void OnMontoChanged();
    partial void OnFecha_HoraChanging(System.DateTime value);
    partial void OnFecha_HoraChanged();
    #endregion
		
		public tbl_IngresosDeCaja()
		{
			this._tbl_EgresosCaja = default(EntityRef<tbl_EgresosCaja>);
			this._tbl_CajaChica = default(EntityRef<tbl_CajaChica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_IngresosCaja", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_IngresosCaja
		{
			get
			{
				return this._Id_IngresosCaja;
			}
			set
			{
				if ((this._Id_IngresosCaja != value))
				{
					if (this._tbl_CajaChica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_IngresosCajaChanging(value);
					this.SendPropertyChanging();
					this._Id_IngresosCaja = value;
					this.SendPropertyChanged("Id_IngresosCaja");
					this.OnId_IngresosCajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Caja", DbType="Int NOT NULL")]
		public int Id_Caja
		{
			get
			{
				return this._Id_Caja;
			}
			set
			{
				if ((this._Id_Caja != value))
				{
					this.OnId_CajaChanging(value);
					this.SendPropertyChanging();
					this._Id_Caja = value;
					this.SendPropertyChanged("Id_Caja");
					this.OnId_CajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Float NOT NULL")]
		public double Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Hora", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Hora
		{
			get
			{
				return this._Fecha_Hora;
			}
			set
			{
				if ((this._Fecha_Hora != value))
				{
					this.OnFecha_HoraChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Hora = value;
					this.SendPropertyChanged("Fecha_Hora");
					this.OnFecha_HoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_IngresosDeCaja_tbl_EgresosCaja", Storage="_tbl_EgresosCaja", ThisKey="Id_IngresosCaja", OtherKey="Id_EgresosCaja", IsUnique=true, IsForeignKey=false)]
		public tbl_EgresosCaja tbl_EgresosCaja
		{
			get
			{
				return this._tbl_EgresosCaja.Entity;
			}
			set
			{
				tbl_EgresosCaja previousValue = this._tbl_EgresosCaja.Entity;
				if (((previousValue != value) 
							|| (this._tbl_EgresosCaja.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_EgresosCaja.Entity = null;
						previousValue.tbl_IngresosDeCaja = null;
					}
					this._tbl_EgresosCaja.Entity = value;
					if ((value != null))
					{
						value.tbl_IngresosDeCaja = this;
					}
					this.SendPropertyChanged("tbl_EgresosCaja");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_CajaChica_tbl_IngresosDeCaja", Storage="_tbl_CajaChica", ThisKey="Id_IngresosCaja", OtherKey="Id_Caja", IsForeignKey=true)]
		public tbl_CajaChica tbl_CajaChica
		{
			get
			{
				return this._tbl_CajaChica.Entity;
			}
			set
			{
				tbl_CajaChica previousValue = this._tbl_CajaChica.Entity;
				if (((previousValue != value) 
							|| (this._tbl_CajaChica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_CajaChica.Entity = null;
						previousValue.tbl_IngresosDeCaja = null;
					}
					this._tbl_CajaChica.Entity = value;
					if ((value != null))
					{
						value.tbl_IngresosDeCaja = this;
						this._Id_IngresosCaja = value.Id_Caja;
					}
					else
					{
						this._Id_IngresosCaja = default(int);
					}
					this.SendPropertyChanged("tbl_CajaChica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_IngresosPorFactura")]
	public partial class tbl_IngresosPorFactura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_IngresosPorFactura;
		
		private int _id_Caja;
		
		private int _Id_Factura;
		
		private decimal _Montototal;
		
		private EntityRef<tbl_CajaChica> _tbl_CajaChica;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_IngresosPorFacturaChanging(int value);
    partial void OnId_IngresosPorFacturaChanged();
    partial void Onid_CajaChanging(int value);
    partial void Onid_CajaChanged();
    partial void OnId_FacturaChanging(int value);
    partial void OnId_FacturaChanged();
    partial void OnMontototalChanging(decimal value);
    partial void OnMontototalChanged();
    #endregion
		
		public tbl_IngresosPorFactura()
		{
			this._tbl_CajaChica = default(EntityRef<tbl_CajaChica>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_IngresosPorFactura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id_IngresosPorFactura
		{
			get
			{
				return this._Id_IngresosPorFactura;
			}
			set
			{
				if ((this._Id_IngresosPorFactura != value))
				{
					this.OnId_IngresosPorFacturaChanging(value);
					this.SendPropertyChanging();
					this._Id_IngresosPorFactura = value;
					this.SendPropertyChanged("Id_IngresosPorFactura");
					this.OnId_IngresosPorFacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Caja", DbType="Int NOT NULL")]
		public int id_Caja
		{
			get
			{
				return this._id_Caja;
			}
			set
			{
				if ((this._id_Caja != value))
				{
					this.Onid_CajaChanging(value);
					this.SendPropertyChanging();
					this._id_Caja = value;
					this.SendPropertyChanged("id_Caja");
					this.Onid_CajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Factura", DbType="Int NOT NULL")]
		public int Id_Factura
		{
			get
			{
				return this._Id_Factura;
			}
			set
			{
				if ((this._Id_Factura != value))
				{
					this.OnId_FacturaChanging(value);
					this.SendPropertyChanging();
					this._Id_Factura = value;
					this.SendPropertyChanged("Id_Factura");
					this.OnId_FacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Montototal", DbType="Decimal(18,2) NOT NULL")]
		public decimal Montototal
		{
			get
			{
				return this._Montototal;
			}
			set
			{
				if ((this._Montototal != value))
				{
					this.OnMontototalChanging(value);
					this.SendPropertyChanging();
					this._Montototal = value;
					this.SendPropertyChanged("Montototal");
					this.OnMontototalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_IngresosPorFactura_tbl_CajaChica", Storage="_tbl_CajaChica", ThisKey="Id_IngresosPorFactura", OtherKey="Id_Caja", IsUnique=true, IsForeignKey=false)]
		public tbl_CajaChica tbl_CajaChica
		{
			get
			{
				return this._tbl_CajaChica.Entity;
			}
			set
			{
				tbl_CajaChica previousValue = this._tbl_CajaChica.Entity;
				if (((previousValue != value) 
							|| (this._tbl_CajaChica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_CajaChica.Entity = null;
						previousValue.tbl_IngresosPorFactura = null;
					}
					this._tbl_CajaChica.Entity = value;
					if ((value != null))
					{
						value.tbl_IngresosPorFactura = this;
					}
					this.SendPropertyChanged("tbl_CajaChica");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_producto")]
	public partial class tbl_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private int _id_categoria;
		
		private string _producto;
		
		private string _modelo;
		
		private string _caracteristicas;
		
		private bool _existencia;
		
		private decimal _precio_compra;
		
		private decimal _precio_venta;
		
		private string _estado;
		
		private EntityRef<tbl_detalle_venta> _tbl_detalle_venta;
		
		private EntityRef<tbl_categoria> _tbl_categoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void OnproductoChanging(string value);
    partial void OnproductoChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OncaracteristicasChanging(string value);
    partial void OncaracteristicasChanged();
    partial void OnexistenciaChanging(bool value);
    partial void OnexistenciaChanged();
    partial void Onprecio_compraChanging(decimal value);
    partial void Onprecio_compraChanged();
    partial void Onprecio_ventaChanging(decimal value);
    partial void Onprecio_ventaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public tbl_producto()
		{
			this._tbl_detalle_venta = default(EntityRef<tbl_detalle_venta>);
			this._tbl_categoria = default(EntityRef<tbl_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int NOT NULL")]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tbl_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this.OnproductoChanging(value);
					this.SendPropertyChanging();
					this._producto = value;
					this.SendPropertyChanged("producto");
					this.OnproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string modelo
		{
			get
			{
				return this._modelo;
			}
			set
			{
				if ((this._modelo != value))
				{
					this.OnmodeloChanging(value);
					this.SendPropertyChanging();
					this._modelo = value;
					this.SendPropertyChanged("modelo");
					this.OnmodeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caracteristicas", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string caracteristicas
		{
			get
			{
				return this._caracteristicas;
			}
			set
			{
				if ((this._caracteristicas != value))
				{
					this.OncaracteristicasChanging(value);
					this.SendPropertyChanging();
					this._caracteristicas = value;
					this.SendPropertyChanged("caracteristicas");
					this.OncaracteristicasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_existencia", DbType="Bit NOT NULL")]
		public bool existencia
		{
			get
			{
				return this._existencia;
			}
			set
			{
				if ((this._existencia != value))
				{
					this.OnexistenciaChanging(value);
					this.SendPropertyChanging();
					this._existencia = value;
					this.SendPropertyChanged("existencia");
					this.OnexistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_compra", DbType="Decimal(18,2) NOT NULL")]
		public decimal precio_compra
		{
			get
			{
				return this._precio_compra;
			}
			set
			{
				if ((this._precio_compra != value))
				{
					this.Onprecio_compraChanging(value);
					this.SendPropertyChanging();
					this._precio_compra = value;
					this.SendPropertyChanged("precio_compra");
					this.Onprecio_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Decimal(18,2) NOT NULL")]
		public decimal precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_producto_tbl_detalle_venta", Storage="_tbl_detalle_venta", ThisKey="id_producto", OtherKey="id_venta", IsUnique=true, IsForeignKey=false)]
		public tbl_detalle_venta tbl_detalle_venta
		{
			get
			{
				return this._tbl_detalle_venta.Entity;
			}
			set
			{
				tbl_detalle_venta previousValue = this._tbl_detalle_venta.Entity;
				if (((previousValue != value) 
							|| (this._tbl_detalle_venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_detalle_venta.Entity = null;
						previousValue.tbl_producto = null;
					}
					this._tbl_detalle_venta.Entity = value;
					if ((value != null))
					{
						value.tbl_producto = this;
					}
					this.SendPropertyChanged("tbl_detalle_venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_categoria_tbl_producto", Storage="_tbl_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tbl_categoria tbl_categoria
		{
			get
			{
				return this._tbl_categoria.Entity;
			}
			set
			{
				tbl_categoria previousValue = this._tbl_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tbl_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_categoria.Entity = null;
						previousValue.tbl_producto.Remove(this);
					}
					this._tbl_categoria.Entity = value;
					if ((value != null))
					{
						value.tbl_producto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(int);
					}
					this.SendPropertyChanged("tbl_categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Tipo")]
	public partial class tbl_Tipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipo;
		
		private string _Tipo;
		
		private EntitySet<Tbl_Factura> _Tbl_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipoChanging(int value);
    partial void Onid_tipoChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    #endregion
		
		public tbl_Tipo()
		{
			this._Tbl_Factura = new EntitySet<Tbl_Factura>(new Action<Tbl_Factura>(this.attach_Tbl_Factura), new Action<Tbl_Factura>(this.detach_Tbl_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipo
		{
			get
			{
				return this._id_tipo;
			}
			set
			{
				if ((this._id_tipo != value))
				{
					this.Onid_tipoChanging(value);
					this.SendPropertyChanging();
					this._id_tipo = value;
					this.SendPropertyChanged("id_tipo");
					this.Onid_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Tipo_Tbl_Factura", Storage="_Tbl_Factura", ThisKey="id_tipo", OtherKey="id_Tipo")]
		public EntitySet<Tbl_Factura> Tbl_Factura
		{
			get
			{
				return this._Tbl_Factura;
			}
			set
			{
				this._Tbl_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Factura(Tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Tipo = this;
		}
		
		private void detach_Tbl_Factura(Tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Tipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_vendedor")]
	public partial class tbl_vendedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vendedor;
		
		private string _id_acceso;
		
		private string _nombre;
		
		private string _apellidos;
		
		private EntityRef<tbl_acceso> _tbl_acceso;
		
		private EntitySet<Tbl_Factura> _Tbl_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendedorChanging(int value);
    partial void Onid_vendedorChanged();
    partial void Onid_accesoChanging(string value);
    partial void Onid_accesoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    #endregion
		
		public tbl_vendedor()
		{
			this._tbl_acceso = default(EntityRef<tbl_acceso>);
			this._Tbl_Factura = new EntitySet<Tbl_Factura>(new Action<Tbl_Factura>(this.attach_Tbl_Factura), new Action<Tbl_Factura>(this.detach_Tbl_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vendedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vendedor
		{
			get
			{
				return this._id_vendedor;
			}
			set
			{
				if ((this._id_vendedor != value))
				{
					this.Onid_vendedorChanging(value);
					this.SendPropertyChanging();
					this._id_vendedor = value;
					this.SendPropertyChanged("id_vendedor");
					this.Onid_vendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_acceso", DbType="NChar(10)")]
		public string id_acceso
		{
			get
			{
				return this._id_acceso;
			}
			set
			{
				if ((this._id_acceso != value))
				{
					this.Onid_accesoChanging(value);
					this.SendPropertyChanging();
					this._id_acceso = value;
					this.SendPropertyChanged("id_acceso");
					this.Onid_accesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_vendedor_tbl_acceso", Storage="_tbl_acceso", ThisKey="id_vendedor", OtherKey="id_acceso", IsUnique=true, IsForeignKey=false)]
		public tbl_acceso tbl_acceso
		{
			get
			{
				return this._tbl_acceso.Entity;
			}
			set
			{
				tbl_acceso previousValue = this._tbl_acceso.Entity;
				if (((previousValue != value) 
							|| (this._tbl_acceso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_acceso.Entity = null;
						previousValue.tbl_vendedor = null;
					}
					this._tbl_acceso.Entity = value;
					if ((value != null))
					{
						value.tbl_vendedor = this;
					}
					this.SendPropertyChanged("tbl_acceso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_vendedor_Tbl_Factura", Storage="_Tbl_Factura", ThisKey="id_vendedor", OtherKey="id_vendedor")]
		public EntitySet<Tbl_Factura> Tbl_Factura
		{
			get
			{
				return this._Tbl_Factura;
			}
			set
			{
				this._Tbl_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Factura(Tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_vendedor = this;
		}
		
		private void detach_Tbl_Factura(Tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_vendedor = null;
		}
	}
}
#pragma warning restore 1591
